version: "2.1"

services:
  api:
    container_name: backend
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: bash -c "gunicorn main:app --worker-class aiohttp.GunicornWebWorker --workers 1 --bind 0.0.0.0:8000 --timeout 600"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: database
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d database -U admin"]
      interval: 30s
      timeout: 10s
      retries: 5
